spring:
  profiles:
    active: ${KOPEVER_CONFIG_ENV:dev}
  application:
    name: kopever-demo
  datasource:
    username: kopever
    password: '*206n#%*qXAS08td4fV2c1eg8s$IpY&4'
    url: jdbc:mysql://127.0.0.1:3306/kopever?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimumIdle: 10
      maximum-pool-size: 100
  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    com.kopever.framework.test.web: ${KOPEVER_LOGGING_LEVEL:INFO}
    com.kopever.framework.test.dao: ${KOPEVER_LOGGING_LEVEL:INFO}

#kopever:
#  framework:
#    filter:
#      logging:
#        enabled: true
#        url-patterns: /*

demo:
  name: kopever-demo
  content: 靠谱就是KOP
  type: 1
  status: 0
  remark: 世界和平
  list:
    - 卡特尔
    - 辛迪加
    - 托拉斯
    - 康采恩
  camel-case-field: OJBK