server:
  port: 7086

spring:
  profiles:
    active: ${KOPEVER_CONFIG_ENV:dev}
    application:
      name: kopever-demo
  #  cloud:
  #    consul:
  #      host: ${KOPEVER_REGISTRY_ADDRESS:localhost}
  #      port: 8500
  #      discovery:
  #        service-name: ${spring.application.name}
  #        prefer-ip-address: true
  #        instance-id: ${spring.cloud.consul.discovery.service-name}:${spring.cloud.client.ip-address}:${server.port}
  #        acl-token: 508ae906-5526-fda0-668c-2a0f115b753a
  #      config:
  #        format: yaml
  #        acl-token: 508ae906-5526-fda0-668c-2a0f115b753a
#  datasource:
#    username: kopever
#    password: $g^xpVxN9!WYAgag45$2Rw$sVyj9vwd^
#    url: jdbc:mysql://193.112.50.99:3306/kopever?useUnicode=true&characterEncoding=utf8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      connection-timeout: 30000
#      idle-timeout: 600000
#      max-lifetime: 1800000
#      minimumIdle: 10
#      maximum-pool-size: 100
  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    com.kopever.framework.test.web: ${KOPEVER_LOGGING_LEVEL:INFO}
    com.kopever.framework.test.dao: ${KOPEVER_LOGGING_LEVEL:INFO}

#kopever:
#  framework:
#    filter:
#      logging:
#        enabled: true
#        url-patterns: /*

demo:
  name: kopever-demo
  content: 靠谱就是KOP
  type: 1
  status: 0
  remark: 世界和平
  list:
    - 卡特尔
    - 辛迪加
    - 托拉斯
    - 康采恩
  camel-case-field: OJBK