spring:
  application:
    name: ${artifactId}${kopdoctor-developer-name}
  cloud:
    consul:
      host: ${kopdoctor-registry-address:127.0.0.1}
      port: ${kopdoctor-registry-port:8500}
      discovery:
        service-name: ${artifactId}
        hostname: ${artifactId}