spring:
  application:
    name: ${rootArtifactId}${kopdoctor-developer-name}
  cloud:
    consul:
      host: ${kopdoctor-registry-address}
      port: 8500
      discovery:
        service-name: ${rootArtifactId}
        hostname: ${rootArtifactId}